import type { GameConfig } from './types'

export const createDefaultGameConfig = (): GameConfig =>
  ({
    basic: {
      reputation: {
        enabled: false,
        threshold: 80,
      },
      reconnectInterval: 300000,
      debug: false,
      task: {
        daily: false,
        weekly: false,
        main: false,
        story: false,
        achieve: false,
      },
      mail: false,
      benefit: {
        buff: false,
        box: false,
        shareRwd: false,
        antiScamBox: false,
      },
      sign: {
        daily: false,
        patch: false,
      },
      pearl: {
        freePearl: false,
        autoHire: false,
        maxHireLevel: 0,
        maxHireTicketUsage: 0,
        autoPearlDraw: false,
        protectEnabled: false,
        autoBuyHireTicket: false,
        maxSpendDmd: 25,
      },
      randomEvent: false,
      feedCat: {
        enabled: false,
        autoRecall: false,
        autoBuyFood: false,
        autoFeed: false,
        autoStroke: false,
      },
      shop: {
        videoFreeGift: false,
        cultivateShop: {
          autoBuy: false,
          maxSpendGold: 0,
        },
        floralShop: {
          enabled: false,
          itemIds: [],
        },
      },
    },
    plant: {
      cultivate: {
        enabled: false,
        autoHarvestEnabled: true,
        videoSpeedUp: false,
        upgradeEnabled: false,
        upgradeQualityEnabled: false,
        upgradeQualities: [1, 2, 3, 4, 5],
        tagetLevel: 20,
      },
      flower: {
        autoUnlockLand: false,
        harvestEnabled: false,
        plantEnabled: false,
        videoSpeedUp: false,
        useSpeedUpTicket: false,
        speedUpTicketScenes: ['normal', 'elves'],
        speedUpTicketMode: 'dailyLimit',

        speedUpTicketMinMinutes: 33,
        speedUpTicketReserve: 0,
        speedUpTicketMax: 20,
        waterThreshold: 0,
        strictLayout: false,
        landGroupSize: 4,
        groupWaterEnabled: false,
        taskMode: true,
        taskLogEnabled: false,
        taskPriorityConfig: {
          顾客订单: 1,
          居民订单: 2,
          花艺售卖: 6,
          莳花纪闻: 3,
          宫廷订单: 4,
          公会竞赛: 3,
        },
        plantingMode: 'count',
        lowStockThreshold: 500,
        freeStyleTemplate: '我的方案A',
        freeStyleList: [
          {
            name: '我的方案A',
            lands: {},
          },
          {
            name: '我的方案B',
            lands: {},
          },
          {
            name: '我的方案C',
            lands: {},
          },
          {
            name: '我的方案D',
            lands: {},
          },
          {
            name: '我的方案E',
            lands: {},
          },
        ],
        minFlowerLevel: 0,
        qualities: [1, 2, 3, 4, 5],
        flowerCount: 4,
        specificFlowerIds: [],
        qualityExcludeEnabled: false,
        qualityExcludeFlowerIds: [],
        countExcludeEnabled: false,
        countExcludeFlowerIds: [],
        lowStockExcludeEnabled: false,
        lowStockExcludeFlowerIds: [],
        plantExcludeMigrated: false,
        plantExcludeFlowerIds: [],
      },
      friendSteal: {
        enabled: false,
        stealElves: false,
        excludeFriendsEnabled: false,
        excludedFriendNames: [],
        onlyStealSpecifiedFriends: false,
        specifiedFriendNames: [],
        onlyStealSpecifiedElves: false,
        specifiedElvesIds: [],
        stealMode: 'quality',
        stealQualities: [1, 2, 3, 4, 5],
        stealFlowerIds: [],
        excludeFlowerIds: [],
        buyStealEnabled: false,
        buyStealCount: 10,
        noStealEnabled: false,
        noStealStart: '01:00',
        noStealEnd: '07:00',
        lateNightConsumeEnabled: false,
      },
      elves: {
        enabled: false,
        selectedElvesIds: [],
        delayedHarvestEnabled: false,
        delayedHarvestMinutes: 10,
        requestAid: false,
        recvAid: false,
        helpFrd: false,
        helpFrdMode: 'limit3',
        dispatch: false,
        dispatchMode: 'doubleFirst',
        dispatchCount: 12,
        speedUpDispatch: false,
        recvDispatch: false,
        recvPass: false,
        recvPassTask: false,
        recvFlowerPass: false,
        recvFlowerPassTask: false,
      },
      water: {
        enabled: false,
        timedEnabled: false,
        minWaterThreshold: 0,
        forceCollectEnabled: false,
        forceCollectTime: '23:30',
      },
      artSell: {
        autoSellArt: false,
        artSellMode: 'vase',
        specifiedArts: [],
        specifiedArtsFull: [],
        flowerArtPerRack: 12,
        rackAutoRefresh: false,
        autoUnlockStand: false,
        recvArtCreateRwd: false,
        recvCollectRwd: false,
        artFirstMake: false,
        stockFirst: false,
      },
      market: {
        autoUnlockShelf: false,
        putEnabled: false,
        putMode: 'inventory',
        specificFlowerIds: [],
        maxSell: 25,
        priceIndex: 2,
        putFlowerPassword: '',
        autoBuyPutCount: false,
        buyPutCount: 0,
        autoBuyFromFriend: false,
        buyMode: 'all',
        buySpecificFlowerIds: [],
        buyQualities: [],
        excludeFlowerIds: [],
        buyFriendNames: [],
        minPutTimeDiff: 0,
      },
    },
    order: {
      resident: {
        normalEnabled: false,
        satinEnabled: false,
        decorateEnabled: false,
        normalMaxNum: 1200,
        satinMaxNum: 120,
        decorateMaxNum: 120,
        timedEnabled: false,
        startTime: '00:00',
        endTime: '00:00',
        qualities: [1, 2, 3, 4, 5],
      },
      customer: {
        enabled: false,
        floralCoinEnabled: false,
        floralCoinCount: 2,
        rejectEnabled: false,
        customerMaxNum: 999,
      },
      palace: {
        enabled: false,
        qualities: [1, 2, 3, 4, 5],
        ignoreQuality: false,
        diamondRefresh: false,
      },
      team: {
        enabled: false,
        oneMore: false,
        submitOnlyCultivatedFlowers: true,
        teamMode: 'quality',
        qualities: [1, 2, 3, 4, 5],
        excludeFlowerIds: [],
        reserveStock: 0,
      },
    },
    union: {
      land: {
        harvest: false,
        autoPlant: false,
        plantMode: 'quality',
        flowers: [1, 2, 3, 4, 5],
        specificFlowerIds: [],
        maxFlowerLevel: 0,
        lowStockThreshold: 1000,
      },
      build: {
        free: false,
        gld: false,
        dmd: false,
      },
      flower: {
        share: false,
        shareMode: 'quality',
        shareQualities: [1, 2, 3, 4, 5],
        shareFlowerIds: [],
        take: false,
        takeMode: 'quality',
        takeQualities: [1, 2, 3, 4, 5],
        takeFlowerIds: [],
      },
      fmlRace: {
        enabled: false,
        autoEnableModules: false,
        useSpeedUpTicketInTask: false,
        minTaskScore: 25,
        minUpgradeTaskScore: 50,
        avoidProgressTask: false,
        onlyUpgradeTask: false,
        othersUpgradeTaskMode: true,
        excludeOthersUpgradeTask: true,
        onlySpecifiedUpgradeTask: false,
        acceptQualifiedNormalTask: false,
        specifiedUpgradePlayers: [],
        harvestTaskFlowerFilterEnabled: false,
        harvestTaskFlowerIds: [],
        taskTypePriority: {
          '2004': 0,
          '3006': 0,
          '3016': 0,
          '3017': 0,
          '3018': 0,
          '3023': 0,
          '3024': 0,
          '3030': 0,
          '3034': 0,
          '3035': 0,
          '3036': 0,
          '3044': 0,
          '3052': 0,
        },
        upgradeTask: false,
        deleteTask: false,
        deleteTaskMaxScore: 0,
        keepSystemUpgrade: false,
        keepPlayerUpgrade: false,
        deleteUnclaimedTask: false,
        deleteUnclaimedMinutes: 60,
        onlyDiamondUpgradeTask: false,
        diamondRefreshTask: false,
        diamondRefreshBelowScore: 14,
        diamondRefreshTargetScore: 24,
        minDiamondUpgradeScore: 24,
        harvestUpgradeRefine: false,
        harvestUpgradeFlowerIds: [],
        diamondUpgradeReserve: 0,
      },
      redPacket: {
        enabled: false,
      },
      fmlForest: {
        enabled: false,
      },
    },
    activity: {
      fmlRace: {
        enabled: true,
      },
      actFmlRedEnvelope: {
        enabled: false,
      },
      cyclicNote: {
        enabled: false,
        unlockSlot: false,
        autoEnableModules: false,
        orderGuard: {
          enabled: false,
          timeRanges: [{ start: '00:00', end: '21:00' }],
        },
      },
      actCyclicStory: {
        enabled: false,
        refreshEnabled: false,
        maxFinshCntPerBatch: 0,
      },
      fishMerge: {
        enabled: false,
        showResult: false,
        autoRestart: false,
      },
      magicBubble: {
        enabled: false,
      },
      fishFun: {
        enabled: false,
        showResult: false,
        autoRestart: false,
        autoClaimEnergy: false,
        speed: 1,
      },
      actElim: {
        enabled: false,
        autoClaimEnergy: false,
        speed: 1,
      },
      zooGameElim: {
        enabled: false,
      },
      lanternFestival: {
        enabled: false,
      },
      actDessert: {
        enabled: false,
        autoClaimEnergy: false,
        useItems: false,
        openBox: false,
        speed: 1,
      },
      actMerge2: {
        enabled: false,
        autoClaimEnergy: false,
        speed: 1,
      },
      actSpool: {
        enabled: false,
        autoClaimReward: false,
        openBox: false,
        autoRestart: false,
        speed: 1,
      },
      actDuanWu: {
        enabled: false,
        autoSign: false,
        autoOpenBox: false,
        giftBuy: false,
      },
      redPacket: {
        enabled: false,
      },
      recvLuck: {
        enabled: false,
      },
      yzCall: {
        enabled: false,
      },
      actJYCALL: {
        enabled: false,
        recvBoxes: false,
      },
      moneyTree: {
        enabled: false,
      },
      actHoney: {
        enabled: false,
      },
      actCardCollect: {
        enabledCardCollect: false,
        enabledSmoke: false,
      },
      actAnniv26Star: {
        enabled: false,
        lightStarsEnabled: false,
      },
      actTwinFlight: {
        enabled: false,
      },
    },
  }) as GameConfig
