// 此文件由 scripts/generate-qhgy-game-config-options.mjs 从奇幻果园导出生成，请勿手工维护。
export const flowerArtOptions: Array<{ value: string; label: string }> = [
  { value: "5001", label: "苹果碗" },
  { value: "5002", label: "喵咪布丁" },
  { value: "5003", label: "瓜漾冰趣" },
  { value: "5004", label: "雪顶山竹冰" },
  { value: "5005", label: "丝绒莓梦" },
  { value: "5006", label: "大鹏展翅" },
  { value: "5007", label: "萌兽藏鲜" },
  { value: "5008", label: "芳桃偎兔" },
  { value: "5009", label: "想开了" },
  { value: "5010", label: "椰豚小憩" },
  { value: "5011", label: "醉夜桑柔" },
  { value: "5101", label: "杏露萌饮" },
  { value: "5201", label: "虹落梅云间" },
  { value: "5202", label: "犬伴双甜" },
  { value: "5203", label: "萌团赴宴" },
  { value: "5204", label: "荔猫嬉秋" },
  { value: "5206", label: "花漾清芳" },
  { value: "5207", label: "绯霞酿酪" },
  { value: "5208", label: "玉兔饮梅" },
  { value: "5209", label: "鲜盅抱玉" },
  { value: "5210", label: "云屿甜梦" },
  { value: "5301", label: "甜喵软憩" },
  { value: "5302", label: "云畔萌啾" },
  { value: "5303", label: "荷风载露" },
  { value: "5304", label: "葵光小筑" },
  { value: "5307", label: "闲趣萌宠" },
  { value: "5311", label: "椰风漫曲" },
  { value: "5401", label: "狐仙泽" },
  { value: "5402", label: "灵花幻域" },
  { value: "5403", label: "鸾鸣九霄" },
  { value: "5404", label: "芳桃映夏" },
  { value: "5415", label: "夏日狂欢" },
]
